### ISSUE TITLE
RuntimeError in plot.py

### ISSUE THREAD

**Issue by MohamedNedal** [antyeates1983/pfss#1]
Hello, 
I was trying to run the file "plot.py" after changing the "bfile" directory to be 
`bfile = 'bPF.nc'
`and the "bPF.nc" is in the same folder of the code, but I got this error: 

> RuntimeError: Failed to process string with tex because latex could not be found 

Can you please tell me how to fix it? 

I'm working on Spyder (Python 3.7) on Windows 10 OS.

**Comment by antyeates1983** [comment]
Hi Mohamed,

Presumably you are missing latex on your local machine. This is only used for the plot labels in line 181-182 of plot.py, so you could just change these lines to not use latex.
E.g. change '$\phi = $%4.2f$^\circ$' to 'lon = %4.2f deg'.

Best regards,
Anthony
________________________________

**Comment by MohamedNedal** [comment]
Hi Anthony, thanks for responding. 

I did that but I got another error: 
```
 line 159, in <module>
    ax.set_axis_bgcolor('k')
AttributeError: 'AxesSubplot' object has no attribute 'set_axis_bgcolor' 
```
